Scaling och kordinatsystem
EdwardKN/Monopoly pull request #104
Opened 2023-05-09 10:03 UTC by EdwardKN

2023-05-09 11:06 UTC, EndyMc commented
### Bugg
Gick in i LocalLobby när min skärm inte var i fullscreen, sedan tvingade den mig ut fullscreen. Jag gick då tillbaka till startmenyn och canvasen är nu inte centrerad.
![image](https://github.com/EdwardKN/Monopoly/assets/82646131/e0c926cc-cd8f-4eff-9e4f-1c1f62a53ab8)

2023-05-09 11:09 UTC, EndyMc commented
Följdfel här:
![image](https://github.com/EdwardKN/Monopoly/assets/82646131/538f67ec-bebf-4468-a2f7-9f510972c0ff)

2023-05-09 21:23 UTC, EndyMc requested changes
- [x] Auktioner ser lite buggade ut (Den svarta baren är felplacerad)
![bild](https://github.com/EdwardKN/Monopoly/assets/82646131/1c21b447-1cb0-41fc-9acb-e6313afcd8e1)
- [x] Det verkar fortfarande finnas glapp vid ~~vissa~~ alla skärmstorlekar, dock på olika ställen.
![bild](https://github.com/EdwardKN/Monopoly/assets/82646131/bf23c31a-80bf-4ff3-87c0-6eae45db47c0)
- [ ] SellButton är fortfarande klickbar även efter den är osynlig. 
![bild](https://github.com/EdwardKN/Monopoly/assets/82646131/3a29f8a4-fe5e-4a88-8061-ee7d231fdd97)
- [x] #105 

Ser bra ut annars.

2023-05-10 07:00 UTC, EdwardKN commented
@EndyMc I vilka fall är sellbutton klickbar när den är osynlig?

2023-05-10 07:02 UTC, EndyMc commented
Det kvittade vilken ruta det var, dock hade jag på inställningen som stänger av mortgage om det nu gjorde någon skillnad.

2023-05-10 07:06 UTC, EndyMc commented
Det var även direkt efter jag sålt rutan, men inte en ruta som jag stod på, då det skulle utlösa den andra oengabuggen.

2023-05-10 08:46 UTC, EndyMc commented on game.js
> +    calculateScaleStuff();
Varför händer detta 4x?

2023-05-10 08:51 UTC, EdwardKN commented on game.js
> +    calculateScaleStuff();
Första gången räknar den ut en grej.
Andra gången använder den den uträknade grejen.
Tredje gången anpassar den till den nya.
Fjärde gången fixar den en gång till

Det funkar!

2023-05-10 08:53 UTC, EndyMc commented on game.js
> +    calculateScaleStuff();
Sure...

2023-05-10 08:53 UTC, merged