Credits, buggfixar och dansk musik
EdwardKN/Monopoly pull request #131
Opened 2023-06-01 14:59 UTC by EdwardKN

2023-06-12 20:38 UTC, EndyMc requested changes
- [ ] ~~Spelare A lade ett bud, spelare B lade gav upp. Spelare A fick inte auktionen automatiskt, utan den vill att spelare A ska lägga mer pengar.~~ Den vinnande spelaren får inte rutan från auktion automatiskt, den måste göra en extra input. (Minimum auktionspris är satt på 20% om det har något med saken att göra)
- [ ] När man sparar ett spel och har Anti-Aliasing avstängt så blir skärmbilden mycket mer pixelerad än vad den borde
![bild](https://github.com/EdwardKN/Monopoly/assets/82646131/f67e74aa-cef0-4904-ad3b-5900f7bee6b9)

2023-06-12 21:15 UTC, EdwardKN commented
> När man sparar ett spel och har Anti-Aliasing avstängt så blir skärmbilden mycket mer pixelerad än vad den borde

Det du har skrivit är fel. Den är inte mer pixelerad än vad den borde vara. Den är helt perfekt på alla sätt. Att trycka ner en 960x540 bild till 480x270 ser aldrig riktigt bra ut. Anti-aliasing hjälper till att det ser bättre ut. Så egentligen borde man inte kunna stänga av anti-aliasing. Men jag gillar att stänga av det för att i fallet av en 1920x1080 skärm i fullskärmsläge ser faktiskt spelet bra ut utan anti-aliasing.

2023-06-13 20:26 UTC, EndyMc requested changes
- [x] ~~Om man har ett spel som man vunnit, så har sparfilen försvunnit från listan. Men man kan fortfarande gå in i menyn för att försöka ladda sparfilen.~~ Gäller nog endast ifall man har vunnit ett spel i en gammal version.
![bild](https://github.com/EdwardKN/Monopoly/assets/82646131/bf90842e-6a4c-48fd-b933-cf85c71a6f1e)
- [ ] Om spelare A inte lägger något bud i auktion så stängs rutan ner utan att spelare B har någon chans att lägga sitt bud. (Samma som innan, men det känns fel att ha det så)
- [ ] Fonten i bankcheck verkar inte ha stor version av vissa bokstäver, dem som jag hittat är: _a_, _å_ och _ä_.
- [ ] I signaturen så finns ÅÄÖ med, men inte i samma kursiverade stil som resten av bokstäverna
- [ ] Texten är inte aligned:
![bild](https://github.com/EdwardKN/Monopoly/assets/82646131/caf3bbd9-0649-4257-b894-c987ab79ad1c)
- [ ] I bilden ovan kan man se att tiden inte är samma för de två spelarna, trots att de borde ha samma tid.
- [ ] Spelen är nog även så långa att det nog är snyggare att visa tiden i hh:mm:ss istället.
- [ ] När spelet slutar så försvinner alla tiles och spelpjäser, innan den byter till nästa scen en frame senare. (Detta fanns som en liten bugg även tidigare)
![bild](https://github.com/EdwardKN/Monopoly/assets/82646131/06c20ec7-a777-4cbc-9815-f69cfdf268cc)
- [ ] Om man startar om sidan, efter man landat på en annan spelares ruta men innan man klickat ner bankchecken. Så kan man göra så att man hamnar på rutan utan att behöva betala. Lyckades få något liknande att hända när jag gick förbi GÅ en gång, jag fick inte de 200kr som jag borde fått genom att förbi.

2023-06-14 09:01 UTC, EdwardKN commented
> * [ ]  När spelet slutar så försvinner alla tiles och spelpjäser, innan den byter till nästa scen en frame senare. (Detta fanns som en liten bugg även tidigare)

Jag kommer inte fixa detta problemet. Orkar inte. Kanske att jag täcker över det med en blank bakgrund istället. Det är inget allvarligt problem.

2023-06-14 15:26 UTC, EndyMc commented
> ~~Första gången man klickar på en sparfil efter att ha gått in i menyn så visar den skärmdumpen på den första spelet, oavsett vilken sparfil man klickar på.~~ Det är något annat som är fel, den visar fel skärmdump för fel sparfil, ibland visar den samma för båda, ibland visar den bilden för den andra sparfilen.

Det är fortfarande något fel med detta, den visar samma bild för båda sparfilerna. Dock bara första gången man klickar på sparfilen efter att gått in i menyn. Efter det så visar den en annan bild för en av sparfilerna, vet inte ifall det är rätt bild, har inget sätt att testa.
![bild](https://github.com/EdwardKN/Monopoly/assets/82646131/b1480dc8-5975-4772-8e88-85daf1965c3b)
![bild](https://github.com/EdwardKN/Monopoly/assets/82646131/8b084278-2d0f-43bb-9870-29e89623bc57)

2023-06-14 15:28 UTC, EndyMc commented
>  Fonten i bankcheck verkar inte ha stor version av vissa bokstäver, dem som jag hittat är: a, å och ä.

Detta är fortfarande kvar, ofixat
![bild](https://github.com/EdwardKN/Monopoly/assets/82646131/2e66c633-5e8e-4f41-b287-931f35922224)

2023-06-14 15:31 UTC, EndyMc commented
Om man laddar om sidan under tiden som en bankcheck är på skärmen så vägrar den ladda
![bild](https://github.com/EdwardKN/Monopoly/assets/82646131/7854fca2-4f61-4744-a88c-d421915f1ab2)

2023-06-14 18:05 UTC, EdwardKN commented
> Om man laddar om sidan under tiden som en bankcheck är på skärmen så vägrar den ladda ![bild](https://user-images.githubusercontent.com/82646131/245845221-7854fca2-4f61-4744-a88c-d421915f1ab2.png)
> 
> Eftersom sidan vägrar ladda så kan jag inte göra mer buggtest...

Inte relaterat till bankcheckar

2023-06-14 18:06 UTC, EdwardKN commented
> > ~Första gången man klickar på en sparfil efter att ha gått in i menyn så visar den skärmdumpen på den första spelet, oavsett vilken sparfil man klickar på.~ Det är något annat som är fel, den visar fel skärmdump för fel sparfil, ibland visar den samma för båda, ibland visar den bilden för den andra sparfilen.
> 
> Det är fortfarande något fel med detta, den visar samma bild för båda sparfilerna. Dock bara första gången man klickar på sparfilen efter att gått in i menyn. Efter det så visar den en annan bild för en av sparfilerna, vet inte ifall det är rätt bild, har inget sätt att testa. 

borde vara fixad

2023-06-14 18:08 UTC, EdwardKN commented
> > Fonten i bankcheck verkar inte ha stor version av vissa bokstäver, dem som jag hittat är: a, å och ä.
> 
> Detta är fortfarande kvar, ofixat

Har bytt font nu

2023-06-16 13:43 UTC, EndyMc approved these changes

2023-06-16 13:44 UTC, merged