Online
EdwardKN/Monopoly pull request #25
Opened 2023-04-18 19:15 UTC by EndyMc

Saker som behövs läggas till:
- [x] Movement
- [x] Community chest / Chance cards
- [x] Auctions
- [x] Tiles / Boardpieces
- [x] Property (Houses/Hotels)
- [x] SSL cert so that this works on github.io
- [x] Lobby under tiden som man väntar på alla att joina
- [x] Skriva in sitt eget användarnamn
- [x] Trading (#22)
- [x] Översätta all text som jag skrivit på engelska
- [x] Uppdatera för att funka med senaste versionen av allt annat
- [x] Add game settings to server config

2023-04-18 19:18 UTC, EndyMc commented
Har jag missat något som bör läggas till?

2023-04-18 20:13 UTC, EndyMc commented
Korten verkar inte fungera helt, när man får en _Gå till X_ så går båda spelare dit

2023-04-19 10:14 UTC, EndyMc commented
Utilities don't work, think this is caused by dicesum not being sent

2023-04-19 10:16 UTC, EndyMc commented
Mortaged building aren't sent across to other clients

2023-04-19 21:02 UTC, EndyMc commented
At random timings, the client seems to send its moveTo event before the animation is finished. This then sometimes makes the client land on a chance card and move to some other tile, which is sent instantly and the animation just disappears

2023-04-22 19:40 UTC, EndyMc commented
Klient 1 tror att den andra spelaren är kvar i finkan och tillåter den därför inte att röra sig, trots att den egentligen tagit sig ut genom att betala. Klient 2 rör dock sin egen spelare på rätt sätt, vilket skapar en desync mellan klienterna.

2023-04-25 14:36 UTC, EndyMc commented
Inte säker på varför, men utan att ändra någon kod gällande det så har olika knappar valt att bli osynliga (fram tills att man börjar hovera över dem) utan någon anledning. Tror dock det verkar hända först efter jag klickat på knappen en gång...

2023-04-25 15:43 UTC, EdwardKN requested changes
Bugg med chanskort. Första personen hamnade på ett chanskort och fix 150kr. Person 2 fick då gå till Simrishamn vilket inte borde hända.

2023-04-25 15:45 UTC, EndyMc commented
> Bugg med chanskort. Första personen hamnade på ett chanskort och fix 150kr. Person 2 fick då gå till Simrishamn vilket inte borde hända.

Det borde vara fixat sedan många versioner tillbaka, har du senaste versionen?

2023-04-25 15:49 UTC, EdwardKN commented
@EndyMc 
<img width="444" alt="Screenshot 2023-04-25 at 17 47 32" src="https://user-images.githubusercontent.com/58272561/234332515-1324ef0b-dd2c-4d76-a133-c9f6a962d5e1.png">

2023-04-25 15:51 UTC, EndyMc commented
Vad står det i serverloggen?

2023-04-25 16:31 UTC, EdwardKN requested changes
Har inte speltestat än, men i övrigt ser det bra ut

2023-04-25 16:31 UTC, EdwardKN commented on README.md
> +# Monopol för fan!
Svenska för fan!

2023-04-25 16:31 UTC, EdwardKN commented on index.html
> +        <button class="waiting" onclick="this.className = this.className == 'ready' ? 'waiting' : 'ready';  Api.readyUp();">Ready Up!</button>
Svenska!

2023-04-25 16:31 UTC, EdwardKN commented on server/Application.js
> +var port = 60000 + Math.round((Math.random() - 0.5) * 10000);
Om man ska port-forwarda så är det lättast om man ska bestämma porten själv istället för slumpmässig

2023-04-25 16:31 UTC, EdwardKN commented on game.js
> +    if (board == undefined) return;
varför?

2023-04-25 16:31 UTC, EdwardKN commented on game.js
> +    if (board == undefined) return;
varför?

2023-04-25 16:36 UTC, EndyMc commented on game.js
> +    if (board == undefined) return;
Tror det är på grund av att board är undefined i lobbyn

2023-04-25 16:37 UTC, EndyMc commented on game.js
> +    if (board == undefined) return;
Tror det är på grund av att board är undefined i lobbyn

2023-04-25 16:38 UTC, EdwardKN commented on game.js
> +    if (board == undefined) return;
ok

2023-04-25 16:38 UTC, EdwardKN commented on game.js
> +    if (board == undefined) return;
ok

2023-04-25 16:45 UTC, EdwardKN commented on server/Application.js
> +var port = 60000 + Math.round((Math.random() - 0.5) * 10000);
vet inte

2023-04-25 16:47 UTC, EndyMc commented on README.md
> +# Monopol för fan!
Okej, men det kommer låta superkonstigt att ha en massa tekniska termer på svenska...

2023-04-25 16:48 UTC, EdwardKN commented on README.md
> +# Monopol för fan!
så kan det va

2023-04-25 16:56 UTC, EndyMc commented on README.md
> +# Monopol för fan!
Översatt

2023-04-27 06:33 UTC, EdwardKN approved these changes
Ser okej ut, borde funka som det ska

2023-04-27 06:46 UTC, merged