Huvudmeny och buggfixar
EdwardKN/Monopoly pull request #36
Opened 2023-04-19 18:25 UTC by EdwardKN

2023-04-25 14:49 UTC, EndyMc requested changes
- Varför sänks maxmängden pengar från 3000kr till 2500kr (Även minimummängden sänks från 500kr till 0kr) när man slår på att man måste vänta X antal rundor innan köp?

- Varför är bara halva gubben där? 
![bild](https://user-images.githubusercontent.com/82646131/234314193-c8cb796a-18da-4335-a44a-4956bd161382.png)

- Varför är det en knapp här? 
![bild](https://user-images.githubusercontent.com/82646131/234314384-51c0f070-fe2e-4c28-a866-cff81620d635.png)

- Står att denna skulle fixas med denna pull request, det har den ej. https://github.com/EdwardKN/Monopoly/issues/42
Ser bra ut annars. =)

2023-04-25 14:59 UTC, EdwardKN commented
@EndyMc 
1. Man ska inte kunna starta en match utan pengar
2. Axel är långsam
3. Ska vara en knapp för att stänga av och på musiken men finns ingen textur än

2023-04-25 15:02 UTC, EndyMc commented
> 1. Man ska inte kunna starta en match utan pengar
Vore det inte enklare för alla ifall min/max mängd pengar är samma oavsett andra inställningar. Typ 500kr - 3000kr som nu

2023-04-25 15:04 UTC, EdwardKN commented
> Vore det inte enklare för alla ifall min/max mängd pengar är samma oavsett andra inställningar. Typ 500kr - 3000kr som nu

Kanske men ibland så vill man köra med att alla startar utan pengar och att man kör några varv för att få pengar innan spelet är igång

2023-04-25 15:34 UTC, EdwardKN commented
@EndyMc Fixat det

2023-04-25 15:42 UTC, EndyMc commented
> > Inte i versionen av din branch som jag har nerladdad
> 
> @EndyMc Vilka knappar syftar du på? Playerborder är de enda som är tillåtna då de inte gör något. Trade är disabled och resten var redan avstängt

Jag körde ett spel med två bottar, där kunde jag öppna playerbordern, och sedan även en trade under tiden som min karaktärs gånganimation höll på

2023-04-25 15:51 UTC, EdwardKN commented
@EndyMc Fixat animationsbuggen

2023-04-25 15:55 UTC, EndyMc commented
> Fixat animationsbuggen

Halvt, trade-knappen kommer inte upp när den ska heller

2023-04-25 15:57 UTC, EdwardKN commented
@EndyMc Jo

2023-04-25 15:59 UTC, EndyMc commented
> @EndyMc Jo

Nope, det är min tur nu, efter jag slagit alla mina tärningskast
![bild](https://user-images.githubusercontent.com/82646131/234335247-6bca4f0e-ab6e-4f08-b2a9-dc86e3a8e043.png)

Jag kan ändå inte trade med botten

2023-04-25 16:27 UTC, EdwardKN commented
@EndyMc Bottarnas namn är inte på fel plats. Ordningen av spelare slumpas när man startar en match

2023-04-25 16:35 UTC, EndyMc commented
> @EndyMc Bottarnas namn är inte på fel plats. Ordningen av spelare slumpas när man startar en match

ok

2023-04-26 07:47 UTC, EndyMc approved these changes

2023-04-26 07:47 UTC, EndyMc commented on .vscode/settings.json
> +    "liveServer.settings.port": 5503
Bytte port igen, lol

2023-04-26 07:47 UTC, merged

2023-04-26 07:48 UTC, ItzAEzClap approved these changes